name: Build & Deploy

on:
  pull_request:
    branches: [ "TEST", "PROD" ]

jobs:
  build-test:
    if: github.base_ref == 'TEST'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy to TEST
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.FTP_HOST_TEST }}
          username: ${{ secrets.FTP_USER_TEST }}
          password: ${{ secrets.FTP_PASS_TEST }}
          local-dir: ./dist
          server-dir: /httpdocs

  build-prod:
    if: github.base_ref == 'PROD'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy to PROD
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.FTP_HOST_PROD }}
          username: ${{ secrets.FTP_USER_PROD }}
          password: ${{ secrets.FTP_PASS_PROD }}
          local-dir: ./dist
          server-dir: /httpdocs
